= API explorer

== Introduction

This project contains a web application used to explore the the documentation
of the oVirt API.

== Using with a live server

In the future this application will be part of the server, and available
from a URL like `/ovirt-engine/apidoc`, but at the moment it isn't. See
the instructions bellow to use it locally.

== Using locally

To use the application locally update the `webconfig.config.js` file to
point the proxy to the URL of your engine:

[source,javascript]
----
proxy: {
  '/ovirt-engine/apidoc/model.json': {
    target: 'http://yourengine.example.com',
    ...
  }
}
----

The application will use that proxy to download the `model.json` that
describes the API from your server.

Then start the webpack development server:

  $ yarn start

This assumes that you have the `yarn` tool installed. If you don't have it, check
the documentation https://yarnpkg.com/lang/en/docs/install[here].

The webpack development server will bind to port 8000 of the `localhost`
address, so to test the application just point your browser to
http://localhost:8000.

During development you can also use the following command to run tests and
static analysis on the code:

  $ yarn test
